### ISSUE TITLE
The run command example should be change 

### ISSUE THREAD

**Issue by StrixzIV** [Delafinn/YoutubeVideoDownloaders#7]
I think in the README.md in the section of "How to use" it is not recommended to use

```sh
python/ python3
```

because it might mislead some user to copy a whole command and it won't execute

Instead, you should write it like this:

## How to use

To download a single video, run:

```sh
python youtube_downloader.py
```

To download a playlist, run:

```sh
python youtube_playlist_downloader.py
```

For Mac and Linux users, change the `python` to `python3` for version specification

**Comment by Delafinn** [comment]
Updating README now

**Comment by Delafinn** [comment]
Updated! Thank you StrixzIV!
